# Generated by Django 5.2.5 on 2025-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0002_alter_task_category_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('morning_routine', 'Morning Routine'), ('career', 'Career'), ('personal_growth', 'Personal Growth'), ('recreation', 'Recreation')], default='personal_growth', max_length=50),
        ),
    ]
